### ISSUE TITLE
Step 4 is not working

### ISSUE THREAD

**Issue by Majber** [Deevian/pathfinder-kingmaker-respec#1]
I pick the save in step 3, I click in step 4 and nothing is happening. I disabled adblock etc, I tried on chrome and edge and in incognito mode and page is open all the time.
Can you please reset my save? 

[Manual_14_to_reset2.zip](https://github.com/Deevian/pathfinder-kingmaker-respec/files/2431375/Manual_14_to_reset2.zip)

**Comment by Majber** [comment]
Its working after disabling auto-use abilities, thank you.

**Comment by Deevian** [comment]
Thanks for opening an issue here :D! 👍
