### ISSUE TITLE
Ekundayo Duplicates his dog

### ISSUE THREAD

**Issue by Zerdude** [Deevian/pathfinder-kingmaker-respec#16]
When you Respec Ekun He gets a new dog
The other stays But doesn't provide vision over the map for some reason
didn't check if letting the old dog die effect anything

**Comment by Deevian** [comment]
This appears to be the case for all pets. I'm working on that today!

**Comment by Deevian** [comment]
I've pushed a fix for that yesterday. Can you try again?

**Comment by Zerdude** [comment]
Looks like you fixed it
But there is another problem i found im opening a new issue for it
