### ISSUE TITLE
Magical items in the chest

### ISSUE THREAD

**Issue by Sharmway** [Deevian/pathfinder-kingmaker-respec#17]
After loading Respec, the magical items left in the safe chest at the capital lose their magic. So a +1 armor becames normal armor, other misc magic items on first equip also lose their abilities, but after save/load equipped it returns, but armors stay "un"magical.

**Comment by Deevian** [comment]
This seems to be a game bug, and one that should be fixed with 1.0.6.

https://github.com/Deevian/pathfinder-kingmaker-respec/issues/3
