### ISSUE TITLE
Respec for companions lev 0

### ISSUE THREAD

**Issue by Majber** [Deevian/pathfinder-kingmaker-respec#20]
I would like to see respec for companions, from 0, just like PC. Its even possible?

**Comment by Deevian** [comment]
+/-

Creating them from 0 is impossible, but we could maybe have level 1 presets (maybe the recommended ones by the game) for each character.

**Comment by Majber** [comment]
I think that optimal solution would be add that lev1 recommended presets for companions as option. (like checkbox - if you want to enable it or just reset to level with which they begin the game)

**Comment by Deevian** [comment]
Yeah, that would work. Still, it implies quite some legwork, and the tool is dropping in popularity against the Nexus mod, so I'm not sure it's worth it. Maybe just to spite the fact that he's forcing a monetary cost on the thing and refusing to share the source code 😄

**Comment by Majber** [comment]
I personally dont like that "not sharing source code attitude" , becouse if that person abandon his project we would be kind of fucked after update that break his code. And here with open source some talented peaople can continue.

**Comment by Deevian** [comment]
Yup, I agree with you. But...

He seems to have a lot more time on his hands, and this seems to already be implemented in the mod, along with keeping traits / buffs / skills and without the hassle of removing the inventory.

Being pragmatic here, it doesn't really pay off to keep working on this when a better tool has came out with more frequent updates. I'll be stopping development of the tool until further notice.
