### ISSUE TITLE
Items lose enchantments after respec

### ISSUE THREAD

**Issue by Deevian** [Deevian/pathfinder-kingmaker-respec#3]
[The Plumber reports](https://steamcommunity.com/app/640820/discussions/0/3393916911747887110/?ctp=5#c3393916911754443396):
> Hey man! I used the tool, tried it out and it did everything it was supposed to... but now none of the masterwork items/+1 items (some have even lost the blue effect behind the item) or stronger items work, I don't get their bonuses- anything from them.
> Thanks for your hard work, also!

[Further info by ubbi](https://steamcommunity.com/app/640820/discussions/0/3393916911747887110/?ctp=5#c3393916911755072719):
>Had the same issue. It will work, if you load a previous savegame where all items still worked (like one BEFORE you saved the extra savegame to respec) and load back to the one AFTER you were finished with respeccing and had equipped everything again.

>For me, I loaded back to a savegame where I was standing in the tavern of the capital. Then I realoaded my "respec savegame" where I was standing in the throne room. 

>Seems like the game just has to remember what the items are supposed to do. ;-)

[Follow up by The Plumber](https://steamcommunity.com/app/640820/discussions/0/3393916911747887110/?ctp=6#c3393916911755768112):
> I tried the same thing, loading one before and loading the game after and it worked perfectly! You have to have the items in your inventory, save, load another save, and then load the new save with the items in your inventory and it will "remember"

**Comment by Deevian** [comment]
Might be fixed by f8fe950fd1728f32b61da07290bef096f0e4f102. Needs further investigation.

**Comment by Deevian** [comment]
This seems to be a bug with chests in the game removing item enchantments.

**Comment by kihot** [comment]
Fixed in 1.0.6 https://steamcommunity.com/games/Pathfinder_Kingmaker/announcements/detail/1708445194413594388
