### ISSUE TITLE
Allow per-character respec

### ISSUE THREAD

**Issue by Deevian** [Deevian/pathfinder-kingmaker-respec#5]
Having to level all characters when you only want to respec one of them is a big hassle, especially at higher levels. The tool should allow players to respec a specific character.

**Comment by akalajzi** [comment]
This should be pretty easy with custom character; they have a property `CustomName` filled, in, what you call `descriptor` when iterating chars. 

For others, we'd need to figure out ids somehow; to know who's who. Maybe they can be pulled out from logs/statistics, but its possible they are generated differently for each save (ie, maybe they're generating companions on the fly, depending on how/when you pick them up).

**Comment by Deevian** [comment]
The Character Editor is already mapping the Blueprints to the names, so we can already use that:

https://github.com/ericfitzgerald/KingmakerCharacterEditor/tree/master/src/app

Having that, there's a couple of things here -- the first one is how to approach it, UI-wise. Do we show the list of all characters right off the bat? We should probably read the file first and check which ones are there. If we do, then we need to make sure that the file is parsed before allowing users to download the modified file. Then again, I guess we can just make the download wait for it, since it shouldn't be that long to process.

Regardless, if you want to go ahead and throw a PR my way, I'd be more than grateful!

**Comment by akalajzi** [comment]
Oh great, didnt even know about that project.  

Yeah, if I manage to find some time today or tomorrow, I'll create a PR. I don't want to respec my whole party anyway :)
